# Generated by Django 4.2 on 2023-04-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Название скидки', models.CharField(max_length=250)),
                ('ID акции в ДО', models.IntegerField()),
                ('Дата начала акции', models.DateTimeField()),
                ('Дата окончания окончания', models.DateTimeField()),
                ('Описание', models.TextField(max_length=1500)),
                ('Файлы', models.FileField(upload_to='')),
                ('manager', models.ManyToManyField(to='shops.shopmanagers')),
            ],
        ),
    ]
