# Generated by Django 4.2 on 2023-05-02 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Действующая акция',
                'verbose_name_plural': 'Действующие акции',
            },
        ),
        migrations.CreateModel(
            name='BugsInDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True, verbose_name='Название бага')),
                ('description', models.TextField(blank=True, default='', max_length=1500, verbose_name='Описание')),
                ('bugDateTime', models.DateTimeField(blank=True, default=None, verbose_name='Дата и время инцидента')),
                ('createDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('N', 'Новый'), ('O', 'Ознакомлен'), ('W', 'В работе'), ('U', 'Требуется разработка'), ('I', 'Нужна информация'), ('D', 'Исправлено')], default='N', max_length=1)),
            ],
            options={
                'verbose_name': 'Баг',
                'verbose_name_plural': 'Баги',
            },
        ),
        migrations.CreateModel(
            name='DiscountData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=250, null=True, verbose_name='Название скидки')),
                ('id_DO', models.IntegerField(blank=True, db_index=True, default=None, verbose_name='ID акции в ДО')),
                ('startDate', models.DateTimeField(blank=True, default=None, verbose_name='Дата начала акции')),
                ('endDate', models.DateTimeField(blank=True, default=None, verbose_name='Дата окончания окончания')),
                ('description', models.TextField(blank=True, default='', max_length=1500, verbose_name='Описание')),
                ('status', models.CharField(choices=[('N', 'Новая'), ('W', 'В работе'), ('T', 'Тестирование'), ('D', 'Релиз')], default='N', max_length=1)),
                ('createDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('isDoneDate', models.DateField(default='2000-01-01')),
                ('slug', models.SlugField(blank=True, verbose_name='slug')),
                ('bugCounter', models.IntegerField(default=0, verbose_name='Количество текущих акций')),
                ('isDone', models.BooleanField(default=False, verbose_name='Подготовлена')),
                ('addDiscountCounters', models.BooleanField(default=False)),
                ('addActiveDiscountCounter', models.BooleanField(default=False)),
                ('manager', models.ManyToManyField(to='shops.shopmanagers')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.CreateModel(
            name='DiscountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Тип скидки')),
            ],
            options={
                'verbose_name': 'Тип акции',
                'verbose_name_plural': 'Тип акций',
            },
        ),
        migrations.CreateModel(
            name='PromocodeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Тип промокода')),
                ('description', models.TextField(blank=True, max_length=1500, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип промокода',
                'verbose_name_plural': 'Тип промокодов',
            },
        ),
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promocode', models.CharField(max_length=250, verbose_name='Промокод')),
                ('promocodeType', models.ManyToManyField(to='discount.promocodetype')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
        migrations.CreateModel(
            name='GalleryFilesWhithErrors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='', verbose_name='Файлы')),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discount.bugsindiscount', verbose_name='баг')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='', verbose_name='Файлы')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discount.discountdata')),
            ],
        ),
        migrations.AddField(
            model_name='discountdata',
            name='promocode',
            field=models.ManyToManyField(to='discount.promocode'),
        ),
        migrations.AddField(
            model_name='discountdata',
            name='shops',
            field=models.ManyToManyField(related_name='shop', to='shops.shop', verbose_name='магазины'),
        ),
        migrations.AddField(
            model_name='discountdata',
            name='type',
            field=models.ManyToManyField(to='discount.discounttype'),
        ),
        migrations.AddField(
            model_name='bugsindiscount',
            name='discount',
            field=models.ManyToManyField(to='discount.discountdata'),
        ),
    ]
