# Generated by Django 4.2 on 2023-05-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugsindiscount',
            name='bugDateTime',
            field=models.DateTimeField(default=None, verbose_name='Дата и время инцидента'),
        ),
        migrations.AlterField(
            model_name='bugsindiscount',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bugsindiscount',
            name='description',
            field=models.TextField(max_length=1500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='bugsindiscount',
            name='discount',
            field=models.ManyToManyField(blank=True, null=True, to='discount.discountdata'),
        ),
        migrations.AlterField(
            model_name='discountdata',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='discountdata',
            name='description',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='discountdata',
            name='endDate',
            field=models.DateTimeField(verbose_name='Дата окончания окончания'),
        ),
        migrations.AlterField(
            model_name='discountdata',
            name='id_DO',
            field=models.IntegerField(db_index=True, verbose_name='ID акции в ДО'),
        ),
        migrations.AlterField(
            model_name='discountdata',
            name='isDoneDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='discountdata',
            name='manager',
            field=models.ManyToManyField(related_name='manager', to='shops.shopmanagers', verbose_name='менеджер'),
        ),
        migrations.AlterField(
            model_name='discountdata',
            name='promocode',
            field=models.ManyToManyField(blank=True, null=True, to='discount.promocode'),
        ),
        migrations.AlterField(
            model_name='discountdata',
            name='slug',
            field=models.SlugField(verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='discountdata',
            name='startDate',
            field=models.DateTimeField(verbose_name='Дата начала акции'),
        ),
        migrations.AlterField(
            model_name='discountdata',
            name='type',
            field=models.ManyToManyField(to='discount.discounttype', verbose_name='Тип акции'),
        ),
        migrations.AlterField(
            model_name='discountfiles',
            name='file',
            field=models.FileField(upload_to='', verbose_name='Файлы'),
        ),
        migrations.AlterField(
            model_name='galleryfileswhitherrors',
            name='file',
            field=models.FileField(upload_to='', verbose_name='Файлы'),
        ),
    ]
