# Generated by Django 4.2 on 2023-04-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_alter_discountdata_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountdata',
            name='ID акции в ДО',
        ),
        migrations.RemoveField(
            model_name='discountdata',
            name='Дата начала акции',
        ),
        migrations.RemoveField(
            model_name='discountdata',
            name='Дата окончания окончания',
        ),
        migrations.RemoveField(
            model_name='discountdata',
            name='Название скидки',
        ),
        migrations.RemoveField(
            model_name='discountdata',
            name='Описание',
        ),
        migrations.RemoveField(
            model_name='discountdata',
            name='Файлы',
        ),
        migrations.AddField(
            model_name='discountdata',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1500, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='discountdata',
            name='endDate',
            field=models.DateTimeField(blank=True, default=None, verbose_name='Дата окончания окончания'),
        ),
        migrations.AddField(
            model_name='discountdata',
            name='files',
            field=models.FileField(blank=True, upload_to='', verbose_name='Файлы'),
        ),
        migrations.AddField(
            model_name='discountdata',
            name='id_DO',
            field=models.IntegerField(blank=True, default=None, verbose_name='ID акции в ДО'),
        ),
        migrations.AddField(
            model_name='discountdata',
            name='startDate',
            field=models.DateTimeField(blank=True, default=None, verbose_name='Дата начала акции'),
        ),
        migrations.AddField(
            model_name='discountdata',
            name='title',
            field=models.CharField(max_length=250, null=True, verbose_name='Название скидки'),
        ),
    ]
