# Generated by Django 4.2 on 2023-05-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_alter_bugsindiscount_bugdatetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountdata',
            name='segment',
            field=models.BooleanField(default=False, verbose_name='Формирование сегмента'),
        ),
    ]
