# Generated by Django 4.2 on 2023-04-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_alter_notes_options'),
        ('discount', '0003_remove_discountdata_id_акции_в_до_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountdata',
            name='shops',
            field=models.ManyToManyField(to='shops.shop'),
        ),
    ]
