# Generated by Django 4.2 on 2023-05-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0003_discountdata_segment'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountdata',
            name='discountSum',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Значение скидки (процент/сумма/баллы)'),
        ),
        migrations.AddField(
            model_name='discountdata',
            name='discountThreshold',
            field=models.IntegerField(blank=True, null=True, verbose_name='Порог скидки'),
        ),
        migrations.AddField(
            model_name='discountdata',
            name='discountThresholdType',
            field=models.CharField(choices=[('P', 'Порог с учетом ПЛ'), ('F', 'Порог без учета ПЛ')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='discountdata',
            name='summation',
            field=models.CharField(choices=[('N', 'Не суммируется с ПЛ'), ('S', 'Суммируется с ПЛ на строку'), ('P', 'Суммируется с ПЛ на документ'), ('B', 'Суммируется с ДК, но не суммируется с ПЛ')], default='N', max_length=1),
        ),
    ]
