# Generated by Django 4.2 on 2023-05-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0005_alter_discountdata_discountthresholdtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugsindiscount',
            name='discount',
            field=models.ManyToManyField(blank=True, to='discount.discountdata'),
        ),
        migrations.AlterField(
            model_name='discountdata',
            name='type',
            field=models.CharField(choices=[('P', 'Скидка процентом'), ('S', 'Скидка суммой'), ('B', 'Бонусные баллы'), ('L', 'Потеряшки'), ('C', 'Кэшбек'), ('G', 'Подарок')], default='P', max_length=1, verbose_name='Тип акции'),
        ),
    ]
