# Generated by Django 4.2 on 2023-04-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0005_discountdata_createdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountdata',
            name='isDone',
            field=models.BooleanField(default=False, verbose_name='Подготовлена'),
        ),
    ]
