# Generated by Django 4.2 on 2023-04-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0006_discountdata_isdone'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountdata',
            name='slug',
            field=models.SlugField(default='reset', max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
