# Generated by Django 4.2 on 2023-04-12 08:44

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_alter_notes_options'),
        ('discount', '0006_discountdata_isdone'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountdata',
            name='idDoneDate',
            field=models.DateField(default='2000-01-01', editable=False),
        ),
        migrations.AddField(
            model_name='discountdata',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='discountdata',
            name='shops',
            field=models.ManyToManyField(related_name='shop', to='shops.shop', verbose_name='магазины'),
        ),
    ]
