# Generated by Django 4.2 on 2023-05-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0006_alter_bugsindiscount_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountdata',
            name='discountThreshold',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Порог скидки'),
        ),
    ]
