# Generated by Django 4.2 on 2023-04-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0007_discountdata_iddonedate_discountdata_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountdata',
            name='idDoneDate',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
