# Generated by Django 4.2 on 2023-04-20 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0008_alter_discountdata_iddonedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugsInDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True, verbose_name='Название бага')),
                ('description', models.TextField(blank=True, default='', max_length=1500, verbose_name='Описание')),
                ('bugDateTime', models.DateTimeField(blank=True, default=None, verbose_name='Дата и время инцидента')),
                ('files', models.FileField(blank=True, upload_to='', verbose_name='Файлы')),
                ('createDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('isFix', models.BooleanField(default=False, verbose_name='FIX')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discount.discountdata')),
            ],
        ),
    ]
