# Generated by Django 4.2 on 2023-05-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0008_alter_bugsindiscount_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountdata',
            name='isDoneDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
