# Generated by Django 4.2 on 2023-05-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0009_alter_discountdata_isdonedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountdata',
            name='type',
            field=models.CharField(choices=[('P', 'Скидка процентом'), ('S', 'Скидка суммой'), ('B', 'Бонусные баллы'), ('L', 'Потеряшки'), ('C', 'Кэшбек'), ('G', 'Подарок'), ('W', 'Лотерея'), ('v', 'Установка цены')], default='P', max_length=1, verbose_name='Тип акции'),
        ),
    ]
