# Generated by Django 4.2 on 2023-04-20 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0009_bugsindiscount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugsindiscount',
            name='files',
        ),
        migrations.CreateModel(
            name='GalleryFilesWhithErrors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='', verbose_name='Файлы')),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discount.bugsindiscount', verbose_name='баг')),
            ],
        ),
    ]
