# Generated by Django 4.2 on 2023-04-20 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0010_remove_bugsindiscount_files_galleryfileswhitherrors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountdata',
            name='files',
        ),
        migrations.CreateModel(
            name='DiscountFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='', verbose_name='Файлы')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discount.discountdata')),
            ],
        ),
    ]
