# Generated by Django 4.2 on 2023-04-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0011_remove_discountdata_files_discountfiles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bugsindiscount',
            options={'verbose_name': 'Баг', 'verbose_name_plural': 'Баги'},
        ),
        migrations.AddField(
            model_name='discountdata',
            name='bugCounter',
            field=models.IntegerField(default=0, verbose_name='Количество текущих акций'),
        ),
    ]
