# Generated by Django 4.2 on 2023-04-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0012_alter_bugsindiscount_options_discountdata_bugcounter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugsindiscount',
            name='discount',
        ),
        migrations.AddField(
            model_name='bugsindiscount',
            name='discount',
            field=models.ManyToManyField(to='discount.discountdata'),
        ),
    ]
