# Generated by Django 4.2 on 2023-04-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0013_remove_bugsindiscount_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugsindiscount',
            name='status',
            field=models.CharField(choices=[('N', 'Новый'), ('O', 'Ознакомлен'), ('W', 'В работе'), ('U', 'Требуется разработка'), ('I', 'Нужна информация'), ('D', 'Исправлено')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='bugsindiscount',
            name='isFix',
            field=models.BooleanField(verbose_name='FIX'),
        ),
    ]
