# Generated by Django 4.2 on 2023-04-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0015_discounttype_promocodetype_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discounttype',
            options={'verbose_name': 'Тип акции', 'verbose_name_plural': 'Тип акций'},
        ),
        migrations.AlterModelOptions(
            name='promocode',
            options={'verbose_name': 'Промокод', 'verbose_name_plural': 'Промокоды'},
        ),
        migrations.AlterModelOptions(
            name='promocodetype',
            options={'verbose_name': 'Тип промокода', 'verbose_name_plural': 'Тип промокодов'},
        ),
        migrations.AddField(
            model_name='discountdata',
            name='promocode',
            field=models.ManyToManyField(to='discount.promocode'),
        ),
        migrations.AlterField(
            model_name='discountdata',
            name='id_DO',
            field=models.IntegerField(blank=True, db_index=True, default=None, verbose_name='ID акции в ДО'),
        ),
        migrations.AlterField(
            model_name='discountdata',
            name='title',
            field=models.CharField(db_index=True, max_length=250, null=True, verbose_name='Название скидки'),
        ),
    ]
