# Generated by Django 4.2 on 2023-04-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0016_alter_discounttype_options_alter_promocode_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountdata',
            name='promocode',
            field=models.ManyToManyField(blank=True, to='discount.promocode'),
        ),
    ]
