# Generated by Django 4.2 on 2023-04-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0018_alter_discountdata_promocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountdata',
            name='promocode',
            field=models.ManyToManyField(to='discount.promocode'),
        ),
    ]
