# Generated by Django 3.2.18 on 2023-04-25 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0020_activediscount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActiveDiscount',
        ),
    ]
