# Generated by Django 3.2.18 on 2023-04-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0021_delete_activediscount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('count', models.IntegerField(default=0)),
                ('discount', models.ManyToManyField(to='discount.DiscountData')),
            ],
            options={
                'verbose_name': 'Действующая акция',
                'verbose_name_plural': 'Действующие акции',
            },
        ),
    ]
