# Generated by Django 3.2.18 on 2023-04-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0022_activediscount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountdata',
            name='idDoneDate',
        ),
        migrations.AddField(
            model_name='discountdata',
            name='isDoneDate',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
