# Generated by Django 3.2.18 on 2023-04-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0023_auto_20230425_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountdata',
            name='isDoneDate',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
