# Generated by Django 3.2.18 on 2023-04-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0024_alter_discountdata_isdonedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountdata',
            name='isDoneDate',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
