# Generated by Django 3.2.18 on 2023-04-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0025_alter_discountdata_isdonedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountdata',
            name='addActiveDiscountCounter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discountdata',
            name='addDiscountCounters',
            field=models.BooleanField(default=False),
        ),
    ]
