# Generated by Django 4.2 on 2023-05-01 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_rename_countcurrentdiscount_shop_countcurrentdiscount_and_more'),
        ('discount', '0026_auto_20230425_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activediscount',
            name='discount',
        ),
        migrations.AddField(
            model_name='activediscount',
            name='shop',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shops.shop'),
        ),
    ]
