# Generated by Django 4.2 on 2023-05-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0031_alter_activediscount_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activediscount',
            name='date',
            field=models.DateField(),
        ),
    ]
