# Generated by Django 4.2 on 2023-05-01 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0032_alter_activediscount_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='activediscount',
            name='discount_data',
            field=models.ManyToManyField(to='discount.discountdata'),
        ),
    ]
