# Generated by Django 4.2 on 2023-04-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentDiscountPerDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discountCounter', models.IntegerField(default=0, verbose_name='Количество акций')),
                ('day', models.DateField(auto_now_add=True, verbose_name='День')),
            ],
        ),
    ]
