# Generated by Django 4.2 on 2023-04-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0002_alter_currentdiscountperday_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Действующая акция',
                'verbose_name_plural': 'Действующие акции',
            },
        ),
        migrations.DeleteModel(
            name='CurrentDiscountPerDay',
        ),
    ]
