# Generated by Django 3.2.18 on 2023-04-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0020_activediscount'),
        ('statistic', '0003_activediscount_delete_currentdiscountperday'),
    ]

    operations = [
        migrations.AddField(
            model_name='activediscount',
            name='discount',
            field=models.ManyToManyField(to='discount.DiscountData'),
        ),
        migrations.AlterField(
            model_name='activediscount',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
