# Generated by Django 3.2.18 on 2023-04-25 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0004_auto_20230425_1040'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActiveDiscount',
        ),
    ]
