# Generated by Django 4.2 on 2023-04-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopManagers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Руководить сети (акции)', models.CharField(max_length=250)),
                ('Контактная информация', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Магазин', models.CharField(max_length=250)),
                ('manager', models.ManyToManyField(to='shops.shopmanagers')),
            ],
        ),
    ]
