# Generated by Django 4.2 on 2023-04-09 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'Магазин', 'verbose_name_plural': 'Магазины'},
        ),
        migrations.AlterModelOptions(
            name='shopmanagers',
            options={'verbose_name': 'Менеджер', 'verbose_name_plural': 'Менеджеры'},
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='Магазин',
            new_name='Наименование магазина',
        ),
        migrations.RemoveField(
            model_name='shopmanagers',
            name='Контактная информация',
        ),
        migrations.AddField(
            model_name='shopmanagers',
            name='Телефон',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Название', models.CharField(max_length=250)),
                ('Дата создания', models.DateField()),
                ('Текст', models.TextField(max_length=2000)),
                ('Файлы', models.FileField(upload_to='')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shopmanagers')),
            ],
        ),
    ]
