# Generated by Django 4.2 on 2023-04-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_alter_shop_options_alter_shopmanagers_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='Дата создания',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='Название',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='Текст',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='Файлы',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='Наименование магазина',
        ),
        migrations.RemoveField(
            model_name='shopmanagers',
            name='Руководить сети (акции)',
        ),
        migrations.RemoveField(
            model_name='shopmanagers',
            name='Телефон',
        ),
        migrations.AddField(
            model_name='notes',
            name='date',
            field=models.DateField(default=None, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='notes',
            name='desc',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='notes',
            name='files',
            field=models.FileField(blank=True, upload_to='', verbose_name='Файлы'),
        ),
        migrations.AddField(
            model_name='notes',
            name='title',
            field=models.CharField(max_length=250, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='shop',
            name='title',
            field=models.CharField(max_length=250, null=True, verbose_name='Наименование магазина'),
        ),
        migrations.AddField(
            model_name='shopmanagers',
            name='name',
            field=models.CharField(max_length=250, null=True, verbose_name='Руководить сети (акции)'),
        ),
        migrations.AddField(
            model_name='shopmanagers',
            name='phone',
            field=models.CharField(blank=True, default='+7', max_length=25, verbose_name='Телефон'),
        ),
    ]
