# Generated by Django 4.2 on 2023-04-09 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_remove_notes_дата_создания_remove_notes_название_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name': 'Заметка', 'verbose_name_plural': 'Заметки'},
        ),
    ]
