# Generated by Django 4.2 on 2023-04-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_alter_notes_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='CountCurrentDiscount',
            field=models.IntegerField(default=0, verbose_name='Количество текущих акций'),
        ),
        migrations.AddField(
            model_name='shop',
            name='countFutureDiscount',
            field=models.IntegerField(default=0, verbose_name='Количество будущих акций'),
        ),
        migrations.AddField(
            model_name='shop',
            name='countPastDiscount',
            field=models.IntegerField(default=0, verbose_name='Количество прошедших акций'),
        ),
    ]
